{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMfyk+bV0ypFdan2UsjdvcP",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Pooja-dotc/TIC_TAC_TOE_AI_CODSOFT/blob/main/TIC_TAC_TOE_AI_codsoft.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "fodzo3-4WZR0",
        "outputId": "2ab7ba7e-7dc9-4a5f-ba10-5f8c9c6d1f77"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Tic-Tac-Toe AI with Minimax and Alpha-Beta Pruning\n",
            "You are 'O'. Enter your move as row (0-2) and column (0-2) separated by space.\n",
            "  |   |  \n",
            "---------\n",
            "  |   |  \n",
            "---------\n",
            "  |   |  \n",
            "---------\n",
            "Your move (row column): 2 2\n",
            "  |   |  \n",
            "---------\n",
            "  |   |  \n",
            "---------\n",
            "  |   | O\n",
            "---------\n",
            "AI's move: \n",
            "  | X |  \n",
            "---------\n",
            "  |   |  \n",
            "---------\n",
            "  |   | O\n",
            "---------\n",
            "Your move (row column): 1 1\n",
            "  | X |  \n",
            "---------\n",
            "  | O |  \n",
            "---------\n",
            "  |   | O\n",
            "---------\n",
            "AI's move: \n",
            "X | X |  \n",
            "---------\n",
            "  | O |  \n",
            "---------\n",
            "  |   | O\n",
            "---------\n",
            "Your move (row column): 2 0\n",
            "X | X |  \n",
            "---------\n",
            "  | O |  \n",
            "---------\n",
            "O |   | O\n",
            "---------\n",
            "AI's move: \n",
            "X | X | X\n",
            "---------\n",
            "  | O |  \n",
            "---------\n",
            "O |   | O\n",
            "---------\n",
            "Congratulations! You won!\n"
          ]
        }
      ],
      "source": [
        "import math\n",
        "\n",
        "# Constants for the players\n",
        "PLAYER_X = \"X\"\n",
        "PLAYER_O = \"O\"\n",
        "EMPTY = \" \"\n",
        "\n",
        "def print_board(board):\n",
        "    for row in board:\n",
        "        print(\" | \".join(row))\n",
        "        print(\"-\" * 9)\n",
        "\n",
        "def evaluate(board):\n",
        "    # Check rows, columns, and diagonals for a winner\n",
        "    for i in range(3):\n",
        "        if board[i][0] == board[i][1] == board[i][2] != EMPTY:\n",
        "            return 1 if board[i][0] == PLAYER_X else -1\n",
        "\n",
        "        if board[0][i] == board[1][i] == board[2][i] != EMPTY:\n",
        "            return 1 if board[0][i] == PLAYER_X else -1\n",
        "\n",
        "    if board[0][0] == board[1][1] == board[2][2] != EMPTY:\n",
        "        return 1 if board[0][0] == PLAYER_X else -1\n",
        "\n",
        "    if board[0][2] == board[1][1] == board[2][0] != EMPTY:\n",
        "        return 1 if board[0][2] == PLAYER_X else -1\n",
        "\n",
        "    return 0  # No winner\n",
        "\n",
        "def is_full(board):\n",
        "    return all(all(cell != EMPTY for cell in row) for row in board)\n",
        "\n",
        "def get_empty_cells(board):\n",
        "    return [(i, j) for i in range(3) for j in range(3) if board[i][j] == EMPTY]\n",
        "\n",
        "def minimax(board, depth, is_maximizing, alpha, beta):\n",
        "    score = evaluate(board)\n",
        "\n",
        "    if score == 1:\n",
        "        return score - depth\n",
        "    if score == -1:\n",
        "        return score + depth\n",
        "    if is_full(board):\n",
        "        return 0\n",
        "\n",
        "    if is_maximizing:\n",
        "        max_eval = -math.inf\n",
        "        for i, j in get_empty_cells(board):\n",
        "            board[i][j] = PLAYER_X\n",
        "            eval = minimax(board, depth + 1, False, alpha, beta)\n",
        "            board[i][j] = EMPTY\n",
        "            max_eval = max(max_eval, eval)\n",
        "            alpha = max(alpha, eval)\n",
        "            if beta <= alpha:\n",
        "                break\n",
        "        return max_eval\n",
        "    else:\n",
        "        min_eval = math.inf\n",
        "        for i, j in get_empty_cells(board):\n",
        "            board[i][j] = PLAYER_O\n",
        "            eval = minimax(board, depth + 1, True, alpha, beta)\n",
        "            board[i][j] = EMPTY\n",
        "            min_eval = min(min_eval, eval)\n",
        "            beta = min(beta, eval)\n",
        "            if beta <= alpha:\n",
        "                break\n",
        "        return min_eval\n",
        "\n",
        "def find_best_move(board):\n",
        "    best_eval = -math.inf\n",
        "    best_move = None\n",
        "\n",
        "    for i, j in get_empty_cells(board):\n",
        "        board[i][j] = PLAYER_X\n",
        "        move_eval = minimax(board, 0, False, -math.inf, math.inf)\n",
        "        board[i][j] = EMPTY\n",
        "\n",
        "        if move_eval > best_eval:\n",
        "            best_eval = move_eval\n",
        "            best_move = (i, j)\n",
        "\n",
        "    return best_move\n",
        "\n",
        "def main():\n",
        "    board = [[EMPTY] * 3 for _ in range(3)]\n",
        "\n",
        "    print(\"Tic-Tac-Toe AI with Minimax and Alpha-Beta Pruning\")\n",
        "    print(\"You are 'O'. Enter your move as row (0-2) and column (0-2) separated by space.\")\n",
        "    print_board(board)\n",
        "\n",
        "    while True:\n",
        "        if is_full(board) or evaluate(board) != 0:\n",
        "            break\n",
        "\n",
        "        user_move = input(\"Your move (row column): \")\n",
        "        user_move = user_move.strip().split()\n",
        "        row, col = int(user_move[0]), int(user_move[1])\n",
        "\n",
        "        if board[row][col] == EMPTY:\n",
        "            board[row][col] = PLAYER_O\n",
        "            print_board(board)\n",
        "\n",
        "            if is_full(board) or evaluate(board) != 0:\n",
        "                break\n",
        "\n",
        "            ai_move = find_best_move(board)\n",
        "            board[ai_move[0]][ai_move[1]] = PLAYER_X\n",
        "            print(\"AI's move: \")\n",
        "            print_board(board)\n",
        "        else:\n",
        "            print(\"Cell is already occupied. Try again.\")\n",
        "\n",
        "    winner = evaluate(board)\n",
        "    if winner == 1:\n",
        "        print(\"Congratulations! You won!\")\n",
        "    elif winner == -1:\n",
        "        print(\"AI wins!\")\n",
        "    else:\n",
        "        print(\"It's a draw!\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ]
}